# ArgoCD documentation:
# enable ingress in the values file `server.ingress.enabled` and either
#       - Add the annotation for ssl passthrough: https://argo-cd.readthedocs.io/en/stable/operator-manual/ingress/#option-1-ssl-passthrough
#       - Set the `configs.params."server.insecure"` in the values file and terminate SSL at your ingress: https://argo-cd.readthedocs.io/en/stable/operator-manual/ingress/#option-2-multiple-ingress-objects-and-hosts
configs:
  params:
    server.insecure: true


  secret:
    #  generated bcrypt hash (MUST be in quotes)
    argocdServerAdminPassword: "$2b$05$C2JfuGCUugsjGcZNHQ4r5uHH16gGSEtKRAuQOXExa.BZsASxnLxuq"
    
    # Required to force ArgoCD to pick up the new password
    argocdServerAdminPasswordMtime: "2026-04-19T00:00:00Z"

redis-ha:
  enabled: false

redis:
  enabled: true

controller:
  replicas: 1

server:
  # Changed to ClusterIP because Ingress will handle the outside traffic
  service:
    type: ClusterIP 
  
  autoscaling:
    enabled: true
    minReplicas: 1
    
  ingress:
    enabled: true
    ingressClassName: nginx
    # ingressClassName: traefik
    https: false
    annotations:
      # NGINX Configuration (Default)
      nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
      nginx.ingress.kubernetes.io/backend-protocol: "HTTPS" # Better than passthrough for Argo
     
      # TRAEFIK Configuration (Uncomment if using Traefik and comment Nginx above)
      # For https:
      # traefik.ingress.kubernetes.io/router.entrypoints: websecure
      # traefik.ingress.kubernetes.io/router.tls: "true"
      # # Tell Traefik to speak HTTP/2 Cleartext to Argo CD
      # traefik.ingress.kubernetes.io/service.serversscheme: h2c

      # For simple http:
      # traefik.ingress.kubernetes.io/router.entrypoints: web
      # traefik.ingress.kubernetes.io/service.serversscheme: h2c

    # tls:
    #   - hostname:
    #       - argocd.localhost

repoServer:
  autoscaling:
    enabled: true
    minReplicas: 1

applicationSet:
  replicas: 1


  